### ISSUE TITLE
Task fail without logs

### ISSUE THREAD

**Issue by vinicvaz** [aws-samples/spark-on-aws-lambda#39]
Hey guys!
I'm newbie to spark and I'm trying to setup a job I have in Glue to run distributed in multiple Lambdas.
I tried to run the sample code you provided for iceberg `sample-accommodations-to-iceberg.py` building the image using `PYSPARK_VERSION=3.2.0` and commenting out the part for writing, just left the read csv part, but the lambda execution is failing without logs.
The `lambda_handler`  was executed, the script file was downloaded but after the job submit the lambda task fail without any logs.

This is the log I'm getting:
![image](https://github.com/aws-samples/spark-on-aws-lambda/assets/50757601/f7ec1daf-4c32-4f42-a5cc-075d65dfcd2e)

In the cloud watch I see the same thing.
Can someone help me?

Thanks!

**Comment by JohnChe88** [comment]
Sure, Just to confirm, It is just Iceberg or the Delta table script failing?

**Comment by JohnChe88** [comment]
Looks like the time out setting in AWS Lambda is 3 sec please increase that to atleast 3 min
