### ISSUE TITLE
Error Running Spark with Hudi  Error: fork/exec /lambda-entrypoint.sh: exec format error Runtime.InvalidEntrypoint

### ISSUE THREAD

**Issue by soumilshah1995** [aws-samples/spark-on-aws-lambda#45]
Here are steps I followed 

# Step 1
```
sam deploy  \
    --template-file sam-imagebuilder.yaml  \
    --stack-name spark-on-lambda-image-builder \
    --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM  \
    --resolve-s3 --parameter-overrides 'ParameterKey=FRAMEWORK,ParameterValue=HUDI'
```

before pushing image I edited this variables in docker file 

```

ENV INPUT_PATH="s3a://XX/accommodations.csv"
ENV OUTPUT_PATH="s3a://XXX/silver/"
ENV AWS_ACCESS_KEY_ID="XX"
ENV AWS_SECRET_ACCESS_KEY="XXX"
ENV AWS_REGION="us-east-1"
ENV AWS_SESSION_TOKEN=""
ENV CUSTOM_SQL=""
```
I have created REPO on ECR and then pushed the image on ECR with commands given on readme file 

when running lambda function I keep getting error   "errorType": "Runtime.InvalidEntrypoint",

![Screenshot 2023-11-01 at 8 08 53 PM](https://github.com/aws-samples/spark-on-aws-lambda/assets/39345855/a22cb5f8-ca15-4056-b734-443574705246)

![Screenshot 2023-11-01 at 8 09 17 PM](https://github.com/aws-samples/spark-on-aws-lambda/assets/39345855/54e5f4e5-1c74-470c-b535-bceab204179a)

**Comment by JohnChe88** [comment]
Seems like an error due the Lambda entry point in Docker file. Could you please try a local execution https://github.com/aws-samples/spark-on-aws-lambda/wiki/Local-testing?
