### ISSUE TITLE
Include S3 based Shuffle storage plugin

### ISSUE THREAD

**Issue by gauravtanwar03** [aws-samples/spark-on-aws-lambda#48]
AWS lambda has a limit of 1024 open File descriptors that leads to task result loss failure if you are merging data in the target tables for building a idempotent ingestion pipelines.

Solution: Use S3 based shuffle storage plugin that can act as a replacement for disk in AWS lambda.

**Comment by JohnChe88** [comment]
@gauravtanwar03 do you have a working code ?

**Comment by JohnChe88** [comment]
We can include

 .config("spark.shuffle.spill", True) \
    .config("spark.shuffle.spill.compress", True) \
    .config("spark.shuffle.compress", True) \
    .config("spark.shuffle.file.buffer", "64k") \
    .config("spark.local.dir", "s3a://your-bucket-name/spark/shuffle/") \
