### ISSUE TITLE
Stuck on Building spark session...

### ISSUE THREAD

**Issue by vivi609kfes** [aws-samples/spark-on-aws-lambda#64]
Hello 
I'm trying to build up a spark on the lambda framework on my lambda function, but I'm facing some problem, when I test local, it is always success, but when I upload and run it in the lambda function always stuck on **Building spark session...**and then finally always got a timeout issue, cos this don't have any error message, don't know how to solve it 
I don't know how to do it and what's the config that I'm probably missing, please help to check ~~

![Screenshot 2024-08-05 at 3 28 29 PM](https://github.com/user-attachments/assets/968f2627-d988-45ac-b478-b7fc407c751c)

**Comment by JohnChe88** [comment]
@vivi609kfes Are you running the Iceberg Script? what is the size of the file ? Have you also tried increasing the time out in AWS Lambda just to get the error message?

**Comment by vivi609kfes** [comment]
@JohnChe88 
I'm running a glue sample script(I don't use any glue library, just use lambda), and I just directly catch the event and then use AWS Lambda spark to clean it.
The weird thing is I can run it successfully locally (runtime less then 5 mins ), but then when I package to a container and upload to AWS Lambda went timeout (and no error message that I can try to check the issue)

thank you so much for such a quick reply !!

**event_size** : JSON file, about 200KB.
**AWS Lambda** : timeout = 5min 
details about lambda config and timeout message: 
![image](https://github.com/user-attachments/assets/83d5b996-24d4-48a4-9094-2cd8d139fa00)

**Comment by vivi609kfes** [comment]
@JohnChe88 
Thank you so much for such a quick reply, I checked with my AWS Lambda resource again and increased the resource about my AWS Lambda, and then it worked!!!! 
thanks again for your answer !!

**Comment by JohnChe88** [comment]
Sure, @vivi609kfes  feel free to contribute and let us know if you are in Dev or PROD
