### ISSUE TITLE
Is any tutorial can help for use same image in ECR (sparkonlambda) move to ECS Fargate

### ISSUE THREAD

**Issue by vivi609kfes** [aws-samples/spark-on-aws-lambda#65]
Hellooo @JohnChe88 
I'm a beginner with ECS, and then I noticed in the previous issue that you mentioned that you're testing this docker image on ECS, Is there any tutorial for using the same image in ECR (sparkonlambda) to move to ECS Fargate?
Can I use the same image to run the container in the ECS ?
If not, is there anything that you recommended to try to implement?

previous issue 
<img width="1065" alt="Screenshot 2024-10-07 at 3 32 26 PM" src="https://github.com/user-attachments/assets/1e306660-fe9e-492c-bea3-88271b06d8f3">

Thanks for your help, I appreciate it!!

**Comment by JohnChe88** [comment]
Hi @vivi609kfes , Have you looked into this branch https://github.com/aws-samples/spark-on-aws-lambda/tree/ecs-changes-v2. It is little old but give you are starting point.

**Comment by JohnChe88** [comment]
closing
